import type { GdiDimensionKey } from "@/lib/types";

export const DIMENSION_KEYWORDS: Record<GdiDimensionKey, string[]> = {
  military_conflict: [
    "war",
    "strike",
    "offensive",
    "ceasefire collapse",
    "troop buildup",
    "missile attack",
    "drone attack",
    "artillery",
    "incursion",
    "clashes",
  ],
  great_power_tension: [
    "sanctions",
    "expulsion",
    "military drills",
    "diplomatic protest",
    "naval standoff",
    "export control",
    "alliance warning",
    "strategic rivalry",
    "cyber attribution",
    "summit breakdown",
  ],
  trade_sanctions: [
    "tariff",
    "sanctions package",
    "export ban",
    "import restriction",
    "entity list",
    "price cap",
    "customs duty",
    "embargo",
    "retaliation",
    "trade dispute",
  ],
  energy_shipping: [
    "shipping disruption",
    "tanker",
    "strait closure",
    "pipeline",
    "lng",
    "crude exports",
    "insurance premium",
    "port shutdown",
    "freight",
    "rerouting",
  ],
  nuclear_miscalculation: [
    "nuclear warning",
    "strategic forces",
    "uranium enrichment",
    "reactor incident",
    "safeguards",
    "missile test",
    "launch detection",
    "deterrence",
    "miscalculation",
    "radiological event",
  ],
};
